# Generated by Django 3.2.8 on 2021-10-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(default='', max_length=20)),
                ('Model', models.CharField(default='', max_length=10)),
                ('Price', models.IntegerField(default='')),
                ('color', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=10)),
                ('Designation', models.CharField(default='', max_length=20)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Password', models.CharField(default='', max_length=8)),
                ('Pic', models.ImageField(default='', upload_to='')),
                ('Phone', models.IntegerField(default='')),
            ],
        ),
    ]
